=== jarrodwhitley/5etools-monster-grabber/schemas/npc.json
{
	"$schema": "http://json-schema.org/draft-07/schema#",
	"title": "Shieldmaiden NPC",
	"description": "JSON Schema for importing Shieldmaiden NPCs",
	"additionalProperties": false,
	"type": "object",
	"properties": {
		"harmless_key": {
			"type": "string",
			"maxLength": 100
		},
		"created": {
			"title": "Created",
			"type": "integer"
		},
		"updated": {
			"title": "Updated",
			"type": "integer"
		},
		"name": {
			"title": "Name",
			"type": "string",
			"minLength": 1,
			"maxLength": 100
		},
		"source": {
			"title": "Source",
			"type": "string",
			"maxLength": 200
		},
		"avatar": {
			"title": "Avatar",
			"type": "string",
			"format": "uri",
			"maxLength": 20000
		},
		"storage_avatar": {
			"title": "Storage avatar",
			"type": "string",
			"format": "uri",
			"maxLength": 20000
		},
		"size": {
			"title": "Size",
			"type": "string",
			"enum": ["Tiny", "Small", "Medium", "Large", "Huge", "Gargantuan"]
		},
		"type": {
			"title": "Type",
			"type": "string",
			"enum": [
				"Aberration",
				"Beast",
				"Celestial",
				"Construct",
				"Dragon",
				"Elemental",
				"Fey",
				"Fiend",
				"Giant",
				"Humanoid",
				"Monstrosity",
				"Ooze",
				"Plant",
				"Swarm of tiny beasts",
				"Undead"
			]
		},
		"subtype": {
			"title": "Subtype",
			"type": "string",
			"maxLength": 100
		},
		"alignment": {
			"title": "Alignment",
			"type": "string",
			"enum": [
				"Any",
				"Any alignment",
				"Unaligned",
				"Lawful good",
				"Neutral good",
				"Chaotic good",
				"Lawful neutral",
				"Neutral",
				"Chaotic neutral",
				"Lawful evil",
				"Neutral evil",
				"Chaotic evil"
			]
		},
		"environment": {
			"type": "array",
			"title": "Environment",
			"items": {
				"type": "string",
				"enum": [
					"arctic",
					"coastal",
					"desert",
					"forest",
					"grassland",
					"hill",
					"mountain",
					"swamp",
					"underdark",
					"underwater",
					"urban"
				]
			}
		},
		"walk_speed": {
			"title": "Walk speed",
			"type": "integer",
			"minimum": 0,
			"maximum": 999
		},
		"swim_speed": {
			"title": "Swim speed",
			"type": "integer",
			"minimum": 0,
			"maximum": 999
		},
		"fly_speed": {
			"title": "Fly speed",
			"type": "integer",
			"minimum": 0,
			"maximum": 999
		},
		"burrow_speed": {
			"title": "Burrow speed",
			"type": "integer",
			"minimum": 0,
			"maximum": 999
		},
		"climb_speed": {
			"title": "Climb speed",
			"type": "integer",
			"minimum": 0,
			"maximum": 999
		},
		"languages": {
			"title": "languages",
			"type": "array",
			"items": {
				"type": "string",
				"maxLength": 100
			}
		},
		"challenge_rating": {
			"title": "Challenge rating",
			"type": "number",
			"maximum": 30,
			"minimum": 0
		},
		"proficiency": {
			"title": "Proficiency",
			"type": "integer",
			"minimum": 0,
			"maximum": 10
		},
		"friendly": {
			"title": "Friendly",
			"type": "boolean"
		},
		"player_id": {
			"title": "Player id",
			"description": "When you give a player a character a companion and that player is controlled by another Shieldmaiden user, the player_id is saved on the NPC, so the user can edit this NPC.",
			"type": "string",
			"maxLength": 50
		},
		"armor_class": {
			"title": "Armor class",
			"type": "integer",
			"minimum": 1,
			"maximum": 99
		},
		"hit_points": {
			"title": "Hit points",
			"type": "integer",
			"minimum": 1,
			"maximum": 9999
		},
		"hit_dice": {
			"title": "Hit dice",
			"type": "string",
			"pattern": "^[0-9]+d[0-9]+$"
		},
		"senses": {
			"title": "senses",
			"type": "object",
			"additionalProperties": false,
			"properties": {
				"blindsight": {
					"title": "Blindsight",
					"type": "object",
					"additionalProperties": false,
					"properties": {
						"blindsight": {
							"type": "boolean"
						},
						"range": {
							"title": "Blindsight range",
							"type": "integer",
							"minimum": 0,
							"maximum": 999
						},
						"comments": {
							"title": "Blindsight comments",
							"type": "string",
							"maxLength": 999
						}
					}
				},
				"darkvision": {
					"title": "Darkvision",
					"type": "object",
					"additionalProperties": false,
					"properties": {
						"darkvision": {
							"type": "boolean"
						},
						"range": {
							"title": "Darkvision range",
							"type": "integer",
							"minimum": 0,
							"maximum": 999
						},
						"comments": {
							"title": "Darkvision comments",
							"type": "string",
							"maxLength": 999
						}
					}
				},
				"tremorsense": {
					"title": "Tremorsense",
					"type": "object",
					"additionalProperties": false,
					"properties": {
						"tremorsense": {
							"type": "boolean"
						},
						"range": {
							"title": "Tremorsense range",
							"type": "integer",
							"minimum": 0,
							"maximum": 999
						},
						"comments": {
							"title": "Tremorsense comments",
							"type": "string",
							"maxLength": 999
						}
					}
				},
				"truesight": {
					"title": "Truesight",
					"type": "object",
					"additionalProperties": false,
					"properties": {
						"truesight": {
							"type": "boolean"
						},
						"range": {
							"title": "Truesight range",
							"type": "integer",
							"minimum": 0,
							"maximum": 999
						},
						"comments": {
							"title": "Truesight comments",
							"type": "string",
							"maxLength": 999
						}
					}
				}
			}
		},
		"strength": {
			"title": "strength",
			"type": "integer",
			"minimum": 0,
			"maximum": 99
		},
		"dexterity": {
			"title": "dexterity",
			"type": "integer",
			"minimum": 0,
			"maximum": 99
		},
		"constitution": {
			"title": "constitution",
			"type": "integer",
			"minimum": 0,
			"maximum": 99
		},
		"intelligence": {
			"title": "intelligence",
			"type": "integer",
			"minimum": 0,
			"maximum": 99
		},
		"wisdom": {
			"title": "wisdom",
			"type": "integer",
			"minimum": 0,
			"maximum": 99
		},
		"charisma": {
			"title": "charisma",
			"type": "integer",
			"minimum": 0,
			"maximum": 99
		},
		"saving_throws": {
			"title": "Saving throws",
			"type": "array",
			"items": {
				"$ref": "#/$defs/ability-select"
			}
		},
		"skills": {
			"title": "Skills",
			"type": "array",
			"items": {
				"$ref": "#/$defs/skill-select"
			}
		},
		"skills_expertise": {
			"title": "Skills expertise",
			"type": "array",
			"items": {
				"$ref": "#/$defs/skill-select"
			}
		},
		"skill_modifiers": {
			"title": "Skill modifiers",
			"type": "object",
			"additionalProperties": false,
			"properties": {
				"acrobatics": { "$ref": "#/$defs/skill-modifier" },
				"animal Handling": { "$ref": "#/$defs/skill-modifier" },
				"arcana": { "$ref": "#/$defs/skill-modifier" },
				"athletics": { "$ref": "#/$defs/skill-modifier" },
				"deception": { "$ref": "#/$defs/skill-modifier" },
				"history": { "$ref": "#/$defs/skill-modifier" },
				"insight": { "$ref": "#/$defs/skill-modifier" },
				"intimidation": { "$ref": "#/$defs/skill-modifier" },
				"investigation": { "$ref": "#/$defs/skill-modifier" },
				"medicine": { "$ref": "#/$defs/skill-modifier" },
				"nature": { "$ref": "#/$defs/skill-modifier" },
				"perception": { "$ref": "#/$defs/skill-modifier" },
				"performance": { "$ref": "#/$defs/skill-modifier" },
				"persuasion": { "$ref": "#/$defs/skill-modifier" },
				"religion": { "$ref": "#/$defs/skill-modifier" },
				"sleight of Hand": { "$ref": "#/$defs/skill-modifier" },
				"stealth": { "$ref": "#/$defs/skill-modifier" },
				"survival": { "$ref": "#/$defs/skill-modifier" }
			}
		},
		"damage_vulnerabilities": {
			"title": "Damage vulnerabilities",
			"type": "array",
			"items": {
				"$ref": "#/$defs/damage-type-select"
			}
		},
		"damage_resistances": {
			"title": "Damage resistances",
			"type": "array",
			"items": {
				"$ref": "#/$defs/damage-type-select"
			}
		},
		"damage_immunities": {
			"title": "Damage immunities",
			"type": "array",
			"items": {
				"$ref": "#/$defs/damage-type-select"
			}
		},
		"condition_immunities": {
			"title": "Condition immunities",
			"type": "array",
			"items": {
				"type": "string",
				"enum": [
					"blinded",
					"charmed",
					"deafened",
					"exhaustion",
					"frightened",
					"grappled",
					"incapacitated",
					"invisible",
					"paralyzed",
					"petrified",
					"poisoned",
					"prone",
					"restrained",
					"stunned",
					"unconscious"
				]
			}
		},
		"caster_ability": {
			"$ref": "#/$defs/ability-select"
		},
		"caster_level": {
			"title": "Caster level",
			"type": "integer",
			"minimum": 1,
			"maximum": 20
		},
		"caster_save_dc": {
			"title": "Caster save DC",
			"type": "integer",
			"minimum": 1,
			"maximum": 99
		},
		"caster_spell_attack": {
			"title": "Caster spell attack",
			"type": "integer",
			"minimum": -10,
			"maximum": 99
		},
		"caster_spell_slots": {
			"title": "Caster spell slots",
			"type": "array",
			"items": {
				"type": ["integer", "null"],
				"maximum": 9,
				"minimum": 1
			},
			"maxItems": 10
		},
		"caster_spells": {
			"title": "Caster spells",
			"type": "object",
			"additionalProperties": {
				"type": "object",
				"additionalProperties": false,
				"properties": {
					"level": {
						"type": "integer",
						"maximum": 9,
						"minimum": -1
					},
					"name": {
						"type": "string",
						"maxLength": 50
					},
					"custom": {
						"type": "boolean"
					}
				},
				"required": ["level", "name"]
			}
		},
		"innate_ability": {
			"$ref": "#/$defs/ability-select"
		},
		"innate_save_dc": {
			"title": "Innate save DC",
			"type": "integer",
			"minimum": 1,
			"maximum": 99
		},
		"innate_spell_attack": {
			"title": "Innate spell attack",
			"type": "integer",
			"minimum": -10,
			"maximum": 99
		},
		"innate_spells": {
			"title": "Innate spells",
			"type": "object",
			"additionalProperties": {
				"type": "object",
				"properties": {
					"limit": {
						"type": "integer",
						"maximum": 9,
						"minimum": -1
					},
					"name": {
						"type": "string",
						"maxLength": 50
					},
					"custom": {
						"type": "boolean"
					}
				},
				"required": ["limit", "name"]
			}
		},
		"special_abilities": {
			"title": "Special abilitles",
			"type": "array",
			"items": {
				"type": "object",
				"additionalProperties": false,
				"properties": {
					"name": { "$ref": "#/$defs/action-name" },
					"recharge": { "$ref": "#/$defs/action-recharge" },
					"limit": { "$ref": "#/$defs/action-limit" },
					"limit_type": { "$ref": "#/$defs/action-limit-type" },
					"desc": { "$ref": "#/$defs/action-desc" },
					"reach": { "$ref": "#/$defs/action-reach" },
					"range": { "$ref": "#/$defs/action-range" },
					"aoe_type": { "$ref": "#/$defs/action-aoe-type" },
					"aoe_size": { "$ref": "#/$defs/action-aoe-size" },
					"options": { "$ref": "#/$defs/action-options" },
					"action_list": { "$ref": "#/$defs/action-list" }
				},
				"required": ["name"]
			}
		},
		"actions": {
			"title": "Actions",
			"type": "array",
			"items": {
				"type": "object",
				"additionalProperties": false,
				"properties": {
					"name": { "$ref": "#/$defs/action-name" },
					"recharge": { "$ref": "#/$defs/action-recharge" },
					"limit": { "$ref": "#/$defs/action-limit" },
					"limit_type": { "$ref": "#/$defs/action-limit-type" },
					"desc": { "$ref": "#/$defs/action-desc" },
					"reach": { "$ref": "#/$defs/action-reach" },
					"range": { "$ref": "#/$defs/action-range" },
					"aoe_type": { "$ref": "#/$defs/action-aoe-type" },
					"aoe_size": { "$ref": "#/$defs/action-aoe-size" },
					"options": { "$ref": "#/$defs/action-options" },
					"action_list": { "$ref": "#/$defs/action-list" }
				},
				"required": ["name"]
			}
		},
		"legendary_count": {
			"title": "Legendary count",
			"type": "integer",
			"minimum": 1,
			"maximum": 9
		},
		"legendary_actions": {
			"title": "Legendary actions",
			"type": "array",
			"items": {
				"type": "object",
				"additionalProperties": false,
				"properties": {
					"legendary_cost": {
						"title": "Legendary cost",
						"type": "integer",
						"description": "How many legendary actions does this action cost.",
						"minimum": 0,
						"maximum": 9
					},
					"name": { "$ref": "#/$defs/action-name" },
					"recharge": { "$ref": "#/$defs/action-recharge" },
					"limit": { "$ref": "#/$defs/action-limit" },
					"limit_type": { "$ref": "#/$defs/action-limit-type" },
					"desc": { "$ref": "#/$defs/action-desc" },
					"reach": { "$ref": "#/$defs/action-reach" },
					"range": { "$ref": "#/$defs/action-range" },
					"aoe_type": { "$ref": "#/$defs/action-aoe-type" },
					"aoe_size": { "$ref": "#/$defs/action-aoe-size" },
					"options": { "$ref": "#/$defs/action-options" },
					"action_list": { "$ref": "#/$defs/action-list" }
				},
				"required": ["name", "legendary_cost"]
			}
		},
		"reactions": {
			"title": "Reactions",
			"type": "array",
			"items": {
				"type": "object",
				"additionalProperties": false,
				"properties": {
					"name": { "$ref": "#/$defs/action-name" },
					"recharge": { "$ref": "#/$defs/action-recharge" },
					"limit": { "$ref": "#/$defs/action-limit" },
					"limit_type": { "$ref": "#/$defs/action-limit-type" },
					"desc": { "$ref": "#/$defs/action-desc" },
					"reach": { "$ref": "#/$defs/action-reach" },
					"range": { "$ref": "#/$defs/action-range" },
					"aoe_type": { "$ref": "#/$defs/action-aoe-type" },
					"aoe_size": { "$ref": "#/$defs/action-aoe-size" },
					"options": { "$ref": "#/$defs/action-options" },
					"action_list": { "$ref": "#/$defs/action-list" }
				},
				"required": ["name"]
			}
		}
	},
	"required": [
		"name",
		"size",
		"type",
		"challenge_rating",
		"armor_class",
		"hit_points",
		"strength",
		"dexterity",
		"constitution",
		"intelligence",
		"wisdom",
		"charisma"
	],

	"$defs": {
		"ability-select": {
			"type": "string",
			"enum": ["strength", "dexterity", "constitution", "intelligence", "wisdom", "charisma"]
		},
		"skill-select": {
			"type": "string",
			"enum": [
				"acrobatics",
				"animal Handling",
				"arcana",
				"athletics",
				"deception",
				"history",
				"insight",
				"intimidation",
				"investigation",
				"medicine",
				"nature",
				"perception",
				"performance",
				"persuasion",
				"religion",
				"sleight of Hand",
				"stealth",
				"survival"
			]
		},
		"skill-modifier": {
			"type": "integer",
			"minimum": -99,
			"maximum": 99
		},
		"damage-type-select": {
			"type": "string",
			"enum": [
				"non_magical_bludgeoning",
				"non_magical_piercing",
				"non_magical_slashing",
				"bludgeoning",
				"piercing",
				"slashing",
				"acid",
				"cold",
				"fire",
				"force",
				"lightning",
				"necrotic",
				"poison",
				"psychic",
				"radiant",
				"thunder"
			]
		},
		"action-name": {
			"title": "Ability name",
			"type": "string",
			"maxLength": 100
		},
		"action-recharge": {
			"title": "Recharge",
			"type": "string",
			"pattern": "^[0-9]+(-[0-9]+)*$|rest$"
		},
		"action-limit": {
			"title": "Limit",
			"type": "integer",
			"minimum": 1,
			"maximum": 9
		},
		"action-limit-type": {
			"title": "Limit type",
			"type": "string",
			"enum": ["day", "turn"]
		},
		"action-desc": {
			"title": "Description",
			"type": "string",
			"maxLength": 5000
		},
		"action-reach": {
			"title": "Reach",
			"type": "integer",
			"minimum": 0,
			"maximum": 999
		},
		"action-range": {
			"title": "Range",
			"type": "string",
			"pattern": "(^[0-9]+(/[0-9]+)*$|^$)"
		},
		"action-aoe-type": {
			"title": "AOE type",
			"type": "string",
			"enum": ["cone", "cube", "cylinder", "line", "radius", "sphere", "square", "square feet"]
		},
		"action-aoe-size": {
			"title": "AOE size",
			"type": "integer",
			"minimum": 0,
			"maximum": 999
		},
		"action-options": {
			"title": "Options",
			"description": "Options allow you to create slightly different rolls for the actions and choose to use this action with one of the options. Think of versatile weapon attacks where you roll a different damage die for 1- or 2-handed attacks.",
			"type": "array",
			"items": {
				"type": "string"
			}
		},
		"action-list": {
			"title": "Action list",
			"type": "array",
			"maxItems": 1,
			"items": {
				"type": "object",
				"additionalProperties": false,
				"properties": {
					"type": {
						"title": "type",
						"type": "string",
						"enum": [
							"melee_weapon",
							"ranged_weapon",
							"spell_attack",
							"save",
							"damage",
							"healing",
							"other"
						]
					},
					"attack_bonus": {
						"title": "Attack bonus",
						"type": "integer",
						"minimum": -10,
						"maximum": 99
					},
					"save_ability": {
						"$ref": "#/$defs/ability-select"
					},
					"save_dc": {
						"title": "Save DC",
						"type": "integer",
						"minimum": 1,
						"maximum": 99
					},
					"rolls": {
						"title": "Rolls",
						"type": "array",
						"items": {
							"type": "object",
							"additionalProperties": false,
							"properties": {
								"damage_type": {
									"$ref": "#/$defs/damage-type-select"
								},
								"magical": {
									"type": "boolean"
								},
								"dice_count": {
									"title": "Dice count",
									"type": "integer",
									"minimum": 1,
									"maximum": 99
								},
								"dice_type": {
									"title": "Dice type",
									"type": "integer",
									"minimum": 1,
									"maximum": 20
								},
								"fixed_val": {
									"title": "Fixed val",
									"type": "integer",
									"minimum": -99,
									"maximum": 99
								},
								"options": {
									"title": "Options",
									"type": "object",
									"additionalProperties": true,
									"properties": {
										"^[A-Za-z0-9\\._%\\+-]+@[A-Za-z0-9\\.-]+\\.[A-Za-z]{2,6}$": {
											"type": "object",
											"additionalProperties": false,
											"properties": {
												"ignore": {
													"title": "Ignore",
													"type": "boolean"
												},
												"damage_type": {
													"$ref": "#/$defs/damage-type-select"
												},
												"dice_count": {
													"title": "Dice count",
													"type": "integer",
													"minimum": 1,
													"maximum": 99
												},
												"dice_type": {
													"title": "Dice type",
													"type": "integer",
													"minimum": 1,
													"maximum": 20
												},
												"fixed_val": {
													"title": "Fixed val",
													"type": "integer",
													"minimum": -99,
													"maximum": 99
												}
											}
										}
									}
								},
								"projectile_count": {
									"title": "Projectile count",
									"type": "integer",
									"minimum": 1,
									"maximum": 99
								},
								"miss_mod": {
									"title": "Miss modifier",
									"type": "number",
									"description": "Multiplier for the rolled damage when the attack misses",
									"minimum": 0,
									"maximum": 2,
									"default": 0
								},
								"save_fail_mod": {
									"title": "Save fail modifier",
									"description": "Multiplier for the rolled damage when the target's saving throw is successful",
									"type": "number",
									"minimum": 0,
									"maximum": 2,
									"default": 0.5
								},
								"special": {
									"title": "special",
									"type": "array",
									"items": {
										"type": "string",
										"enum": ["siphon_full", "siphon_half", "drain"]
									}
								}
							}
						}
					}
				}
			}
		}
	}
}

=== jarrodwhitley/5etools-monster-grabber/example.json
{
  "actions": [
    {
      "action_list": [
        {
          "type": "other",
          "rolls": []
        }
      ],
      "desc": "The aspect makes one Bite attack, one Claw attack, and one Tail attack.",
      "name": "Multiattack"
    },
    {
      "action_list": [
        {
          "attack_bonus": 19,
          "rolls": [
            {
              "damage_type": "piercing",
              "dice_count": 2,
              "dice_type": 12,
              "fixed_val": 10,
              "miss_mod": 0,
              "special": []
            }
          ],
          "type": "melee_weapon"
        }
      ],
      "desc": "Melee Weapon Attack: +19 to hit, reach 20 ft., one target. Hit: 23 (2d12 + 10) piercing damage plus 22 (4d10) force damage.",
      "name": "Bite",
      "reach": 20
    },
    {
      "action_list": [
        {
          "attack_bonus": 19,
          "rolls": [
            {
              "damage_type": "slashing",
              "dice_count": 2,
              "dice_type": 10,
              "fixed_val": 10,
              "miss_mod": 0,
              "special": []
            }
          ],
          "type": "melee_weapon"
        }
      ],
      "desc": "Melee Weapon Attack: +19 to hit, reach 15 ft., one target. Hit: 21 (2d10 + 10) slashing damage. If the target is a Huge or smaller creature, it is grappled (escape DC 20) and is {@condition restrained} until this grapple ends. The aspect can have only one creature {@condition grappled} this way at a time.",
      "name": "Claw",
      "reach": 15
    },
    {
      "action_list": [
        {
          "attack_bonus": 19,
          "rolls": [
            {
              "damage_type": "bludgeoning",
              "dice_count": 2,
              "dice_type": 12,
              "fixed_val": 10,
              "miss_mod": 0,
              "special": []
            }
          ],
          "type": "melee_weapon"
        }
      ],
      "desc": "Melee Weapon Attack: +19 to hit, reach 15 ft., one target. Hit: 23 (2d12 + 10) bludgeoning damage. If the target is a creature, it must succeed on a DC 27 Strength saving throw or be knocked prone.",
      "name": "Tail",
      "reach": 15
    },
    {
      "action_list": [
        {
          "type": "other",
          "rolls": []
        }
      ],
      "desc": "The aspect uses one of the following breath weapons: Exalting Breath\nundefined Platinum Breath\nundefined",
      "name": "Breath Weapon",
      "recharge": "5-6"
    }
  ],
  "alignment": "Lawful good",
  "armor_class": 23,
  "avatar": "https://5e.tools/img/bestiary/tokens/FTD/Aspect%20of%20Bahamut.webp",
  "burrow_speed": 60,
  "challenge_rating": 30,
  "charisma": 30,
  "condition_immunities": [
    "charmed",
    "deafened",
    "frightened",
    "paralyzed",
    "stunned"
  ],
  "constitution": 29,
  "created": 1774026178244,
  "damage_immunities": [
    "bludgeoning",
    "piercing",
    "slashing"
  ],
  "dexterity": 18,
  "fly_speed": 120,
  "harmless_key": "1774026178244-dln6vbde",
  "hit_dice": "30d20",
  "hit_points": 585,
  "intelligence": 25,
  "languages": [
    "Common",
    "Draconic"
  ],
  "name": "Aspect of Bahamut",
  "saving_throws": [
    "constitution",
    "intelligence",
    "wisdom",
    "charisma"
  ],
  "senses": {
    "truesight": {
      "comments": "",
      "range": 120,
      "truesight": true
    }
  },
  "size": "Gargantuan",
  "skills": [
    "insight",
    "perception",
    "persuasion"
  ],
  "special_abilities": [
    {
      "desc": "If the aspect would be reduced to 0 hit points, his current hit point total instead resets to 500 hit points, he recharges his Breath Weapon, and he regains any expended uses of Legendary Resistance. Additionally, the aspect can now use the options in the \"Mythic Actions\" section for 1 hour. Award a party an additional 155,000 XP (310,000 XP total) for defeating the aspect of Bahamut after his Platinum Brilliance activates.",
      "name": "Platinum Brilliance (Recharges after a Short or Long Rest)"
    },
    {
      "desc": "If the aspect fails a saving throw, he can choose to succeed instead.",
      "name": "Legendary Resistance (5/Day)"
    },
    {
      "desc": "The aspect magically transforms into any Humanoid or Beast, while retaining his game statistics (other than his size). This transformation ends if the aspect is reduced to 0 hit points or if he uses a bonus action to end it.",
      "name": "Change Shape"
    }
  ],
  "strength": 30,
  "swim_speed": 60,
  "type": "Dragon",
  "updated": 1774026178244,
  "walk_speed": 60,
  "wisdom": 28
}
